DROP DATABASE IF EXISTS checklist_db;
CREATE DATABASE checklist_db;

USE checklist_db;

CREATE TABLE checklist(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
todo_name VARCHAR(50) NOT NULL,
done BOOLEAN
);
